// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOcLpNI8OhAYZ92Eno3Tjqf9KuYNvJGic',
    appId: '1:250599160578:web:2acc9b3ae575215172601b',
    messagingSenderId: '250599160578',
    projectId: 'personal-743af',
    authDomain: 'personal-743af.firebaseapp.com',
    storageBucket: 'personal-743af.appspot.com',
    measurementId: 'G-B0N19TMX2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT204t4VpbYgveAejMJVpf5kZ_FCLT0tA',
    appId: '1:250599160578:android:96e0ed7ef06a485b72601b',
    messagingSenderId: '250599160578',
    projectId: 'personal-743af',
    storageBucket: 'personal-743af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCc-rEoN-7stZvxwWKXUdp_idOz6Ag_sI',
    appId: '1:250599160578:ios:3d9e70e69cabb14072601b',
    messagingSenderId: '250599160578',
    projectId: 'personal-743af',
    storageBucket: 'personal-743af.appspot.com',
    iosClientId: '250599160578-gom9jkkqb33hjid6eqmmpqeluf7gtpiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.webterminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCc-rEoN-7stZvxwWKXUdp_idOz6Ag_sI',
    appId: '1:250599160578:ios:3d9e70e69cabb14072601b',
    messagingSenderId: '250599160578',
    projectId: 'personal-743af',
    storageBucket: 'personal-743af.appspot.com',
    iosClientId: '250599160578-gom9jkkqb33hjid6eqmmpqeluf7gtpiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.webterminal',
  );
}
